name: heart_rate
description: "Heart Rate Monitor App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # Camera functionality
  camera: ^0.11.2
  
  # Permissions
  permission_handler: ^12.0.1
  
  # Charts for heart rate visualization
  fl_chart: ^1.0.0
  
  # Local storage
  shared_preferences: ^2.5.3
  
  # Date formatting
  intl: ^0.20.2
  
  # Wakelock to keep screen on during measurement
  wakelock_plus: ^1.3.2
  
  # FFT for advanced signal processing
  fftea: ^1.5.0+1
  
  # Localization
  easy_localization: ^3.0.8

  # Routing and navigation
  go_router: ^16.1.0
  google_nav_bar: ^5.0.7
  provider: ^6.1.5

  # UI
  flutter_spinkit: ^5.2.1
  responsive_sizer: ^3.3.1
  line_icons: ^2.0.3

  #splash
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/splash/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
    - family:  CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

# Flutter Native Splash configuration
flutter_native_splash:
  color: "#E53E3E"
  image: assets/images/splash/logo.png
 
  # Android için
  android_12:
    # Android 12+ için özel ayarlar
    image: assets/images/splash/android12.png
    color: "#E53E3E"
    
  branding: assets/images/splash/secondary_asset.png
  branding_mode: bottom
  branding_bottom_padding: 24
  
  # Dark mode desteği
  color_dark: "#C53030"  # Primary dark color
  image_dark: assets/images/splash/logo.png
  branding_dark: assets/images/splash/secondary_asset.png
