name: heart_rate
description: "Heart Rate Monitor App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  #Firebase
  firebase_core: ^4.0.0
  firebase_analytics: ^12.0.0
  firebase_database: ^12.0.0
  
  # Camera functionality
  camera: ^0.11.2
  
  # Permissions
  permission_handler: ^12.0.1
  
  # Charts for heart rate visualization
  fl_chart: ^1.0.0
  fraction: ^5.0.5
  
  # Local storage
  shared_preferences: ^2.5.3
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  envied: ^1.2.0
  
  # Date formatting
  intl: ^0.20.2
  
  # UUID generation
  uuid: ^4.5.1
  
  # Wakelock to keep screen on during measurement
  wakelock_plus: ^1.3.2
  
  # FFT for advanced signal processing
  fftea: ^1.5.0+1
  
  # Localization
  easy_localization: ^3.0.8

  # Routing and navigation
  go_router: ^16.1.0
  animated_bottom_navigation_bar: ^1.4.0
  provider: ^6.1.5
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  json_annotation: ^4.9.0

  #info
  package_info_plus: ^8.3.1
  open_store: ^0.5.0

  # UI
  flutter_spinkit: ^5.2.1
  responsive_sizer: ^3.3.1
  line_icons: ^2.0.3
  lottie: ^3.3.1
  flutter_svg: ^2.2.0
  rive: ^0.13.20
  blur: ^4.0.2
  sliding_up_panel: ^2.0.0+1
  cached_network_image: ^3.4.1
  animations: ^2.0.11
  badges: ^3.1.2
  flutter_slidable: ^4.0.1
  dio: ^5.9.0
  top_snackbar_flutter: ^3.3.0
  animated_text_kit: ^4.2.3
  flutter_custom_clippers: ^2.1.0

  #splash
  flutter_native_splash: ^2.4.6
  
  # App icons
  flutter_launcher_icons: ^0.14.3

  # Export and sharing
  pdf: ^3.11.3
  path_provider: ^2.1.5
  share_plus: ^11.1.0
  url_launcher: ^6.3.2
  
  # App review
  rate_my_app: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.9.3
  build_runner: ^2.4.15
  json_serializable: ^6.9.0
  envied_generator: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/splash/
    - assets/images/
    - assets/json/
    - assets/svg/
    - assets/rive/
    - assets/images/general/
    - assets/images/home/
    - assets/svg/general/

  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Regular.ttf
        - asset: fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: fonts/Urbanist-Thin.ttf
          weight: 100

# Flutter Native Splash configuration
flutter_native_splash:
  color: "#E53E3E"
  image: assets/images/splash/logo.png
 
  # Android için
  android_12:
    # Android 12+ için özel ayarlar
    image: assets/images/splash/android12.png
    color: "#E53E3E"
    
  branding: assets/images/splash/brand.png
  branding_mode: bottom
  
  # Dark mode desteği
  color_dark: "#C53030"  # Primary dark color
  image_dark: assets/images/splash/logo.png
  branding_dark: assets/images/splash/brand.png

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splash/new_logo.png"
  remove_alpha_ios: true # iOS App Store için alpha channel'ı kaldır
  min_sdk_android: 21 # android min sdk min:16, default 21
  
  # Adaptive icon için (Android 8.0+)
  adaptive_icon_background: "#FD4452" # Heart red background
  adaptive_icon_foreground: "assets/images/splash/logo_foreground.png"
  
  web:
    generate: true
    image_path: "assets/images/splash/logo.png"
    background_color: "#E53E3E"
    theme_color: "#E53E3E"
  windows:
    generate: true
    image_path: "assets/images/splash/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
