// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEwtN_ADGRH4yzv9-tv2s5durINcq1lIU',
    appId: '1:753212905264:web:20ea5a715811eedf6e5af5',
    messagingSenderId: '753212905264',
    projectId: 'heart-rate-eeb45',
    authDomain: 'heart-rate-eeb45.firebaseapp.com',
    storageBucket: 'heart-rate-eeb45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcYQox_hZ_xx644nMIW0LMYGFJ9YTCvZA',
    appId: '1:753212905264:android:1abddb5aa07f32526e5af5',
    messagingSenderId: '753212905264',
    projectId: 'heart-rate-eeb45',
    storageBucket: 'heart-rate-eeb45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCO6wTM13k1MC7Y_QfMK8mWv1CFWYFsQA',
    appId: '1:753212905264:ios:4220a2e3d7edf3c76e5af5',
    messagingSenderId: '753212905264',
    projectId: 'heart-rate-eeb45',
    storageBucket: 'heart-rate-eeb45.firebasestorage.app',
    iosBundleId: 'co.wiserapps.heartrate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCO6wTM13k1MC7Y_QfMK8mWv1CFWYFsQA',
    appId: '1:753212905264:ios:bfc09026547ed2176e5af5',
    messagingSenderId: '753212905264',
    projectId: 'heart-rate-eeb45',
    storageBucket: 'heart-rate-eeb45.firebasestorage.app',
    iosBundleId: 'com.example.heartRate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEwtN_ADGRH4yzv9-tv2s5durINcq1lIU',
    appId: '1:753212905264:web:6f139c4ad842678d6e5af5',
    messagingSenderId: '753212905264',
    projectId: 'heart-rate-eeb45',
    authDomain: 'heart-rate-eeb45.firebaseapp.com',
    storageBucket: 'heart-rate-eeb45.firebasestorage.app',
  );
}
