// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:heart_rate/models/recipe/ingredient.dart';
import 'package:heart_rate/models/recipe/nutrition.dart';
import 'package:heart_rate/models/recipe/recipes.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(IngredientAdapter());
    registerAdapter(NutritionAdapter());
    registerAdapter(RecipeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(IngredientAdapter());
    registerAdapter(NutritionAdapter());
    registerAdapter(RecipeAdapter());
  }
}
